# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= axi_stream_eth_fcs_check
TOP_FILE          ?= ../src/axi_stream_eth_fcs_check.sv
TOP_DEPS          ?=

TESTBENCH_MODULE  ?= axi_stream_eth_fcs_check_tb
TESTBENCH_FILE    ?= ../src/axi_stream_eth_fcs_check_tb.sv
TESTBENCH_DEPS    ?= ../../axi_stream_eth_fcs_gen/src/axi_stream_eth_fcs_gen.sv


include ../../../../Makefiles/common.mk
include ../../../../Makefiles/wavedisp.mk
include ../../../../Makefiles/iverilog.mk
include ../../../../Makefiles/verilator.mk
