# Logic Unit Makefile
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= hynoc_router_base
TOP_FILE          ?= ../src/hynoc_router_base.v
TOP_DEPS          ?= ../../hynoc_ingress ../../hynoc_egress


include ../../../../Makefiles/common.mk
include ../../../../Makefiles/verilator.mk
include ../../../../Makefiles/xilinx.mk
