MAIN_TEX_FILE = ../base.tex
PDF_FILE = test.pdf
DEP_TEX_FILES = brief.tex features.tex iptitle.tex iptable.tex content.tex
BIB_FILE = references.bib
EXTRA_TEXINPUTS =

include ../../../makefiles/pdflatex.mk
