# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= bin2gray
TOP_FILE          ?= ../src/bin2gray.v

TESTBENCH_MODULE  ?= bin2gray_tb
TESTBENCH_FILE    ?= ../src/bin2gray_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
