# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/bin2gray_tb.v
TESTBENCH_MODULE  = bin2gray_tb

VCD_FILE          = bin2gray_tb.vcd

TOP_FILE          = ../src/bin2gray.v
TOP_MODULE        = bin2gray

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
