# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= sclkfiforeg
TOP_FILE          ?= ../src/sclkfiforeg.v

TESTBENCH_MODULE  ?= sclkfiforeg_tb
TESTBENCH_FILE    ?= ../src/sclkfiforeg_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
include ../../../Makefiles/common.mk
