# Logic Unit Makefile
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= hynoc_egress
TOP_FILE          ?= ../src/hynoc_egress.v
TOP_DEPS          ?= ../../../../lib/prra

TESTBENCH_MODULE  ?= hynoc_egress_tb
TESTBENCH_FILE    ?= ../src/hynoc_egress_tb.v


include ../../../../Makefiles/common.mk
include ../../../../Makefiles/iverilog.mk
include ../../../../Makefiles/verilator.mk
include ../../../../Makefiles/vivado.mk
