# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= crc32
TOP_FILE          ?= ../src/crc32.sv
TOP_DEPS          ?=

TESTBENCH_MODULE  ?= crc32_tb
TESTBENCH_FILE    ?= ../src/crc32_tb.sv
TESTBENCH_DEPS    ?=

VIVADO_BOARDFILE  ?= crc32.xdc
VIVADO_PROJECT_OOC ?= 1

include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/vivado.mk
