# Logic Unit Makefile
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= prra
TOP_FILE          ?= ../src/prra.v
TOP_DEPS          ?= ../../prra_lut/src/prra_lut.v

TESTBENCH_MODULE  ?= prra_tb
TESTBENCH_FILE    ?= ../src/prra_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
