# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= asdpmem
TOP_FILE          ?= ../src/asdpmem.v

TESTBENCH_MODULE  ?= asdpmem_tb
TESTBENCH_FILE    ?= ../src/asdpmem_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
