# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/asdpmem_tb.v
TESTBENCH_MODULE  = asdpmem_tb

VCD_FILE          = asdpmem_tb.vcd

TOP_FILE          = ../src/asdpmem.v
TOP_MODULE        = asdpmem

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
