// SPDX-License-Identifier: CERN-OHL-P-2.0
// Copyright (c) 2026 Christophe Clienti
//
// This source describes Open Hardware and is licensed under the CERN-OHL-P v2.
// You may redistribute and modify this file under the terms of the CERN-OHL-P v2
// (https://ohwr.org/cern_ohl_p_v2.txt).
//
// This source is distributed WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING
// OF MERCHANTABILITY, SATISFACTORY QUALITY AND FITNESS FOR A PARTICULAR PURPOSE.
// Please see the CERN-OHL-P v2 for applicable conditions.

//-----------------------------------------------------------------------------
// Title         : TCP Model Package
//-----------------------------------------------------------------------------
// File          : tcp_model_pkg_tb.sv
// Author        : Christophe Clienti <cclienti@wavecruncher.net>
// Created       : 2026-09-12
// Last modified : 2026-09-12
//-----------------------------------------------------------------------------
// Description: Self-check of tcp_model_pkg. The builders are anchored
// to nine whole frames produced by project/gen_vectors.py, a pure
// Python implementation that shares nothing with the package, and the
// IPv4 checksum to the published RFC 1071 example; the parsers must
// accept those frames and give back every field. Then the parsers are
// shown to refuse each kind of damage they are meant to catch, the
// option walker is fed lists the builder never produces, a few hundred
// random headers and payloads go through build and parse and back, and
// the sequence-space comparisons are checked around the wrap.
//
// Reports tcp_model_pkg_tb: ALL TESTS PASSED or N ERROR(S).

`timescale 1 ns / 100 ps

module tcp_model_pkg_tb;
    import tcp_model_pkg::*;

    //----------------------------------------------------------------
    // Golden vectors
    //----------------------------------------------------------------
    // Generated by project/gen_vectors.py, do not edit by hand
    localparam string V_SYN = "02000000002a3c970e12345608004500002c4e2140004006b72ec0a85a01c0a85a2ac82200171a2b3c4d000000006002faf049070000020405b4";
    localparam string V_SYN_ACK = "3c970e12345602000000002a08004500002c0000400040060550c0a85a2ac0a85a010017c822000010001a2b3c4e601208002be70000020405b4";
    localparam string V_ACK = "02000000002a3c970e1234560800450000284e2240004006b731c0a85a01c0a85a2ac82200171a2b3c4e000010015010faf050b30000";
    localparam string V_DATA = "02000000002a3c970e12345608004500002d4e2340004006b72bc0a85a01c0a85a2ac82200171a2b3c4e000010015018faf00cd4000068656c6c6f";
    localparam string V_ECHO = "3c970e12345602000000002a08004500002d000040004006054fc0a85a2ac0a85a010017c822000010011a2b3c53501807fbffc4000068656c6c6f";
    localparam string V_ODD = "02000000002a3c970e12345608004500002b4e2440004006b72cc0a85a01c0a85a2ac82200171a2b3c53000010065018faf08c3b0000616263";
    localparam string V_FIN = "02000000002a3c970e1234560800450000284e2540004006b72ec0a85a01c0a85a2ac82200171a2b3c56000010065011faf050a50000";
    localparam string V_RST = "3c970e12345602000000002a0800450000280000400040060554c0a85a2ac0a85a010017c822000010061a2b3c57501400004b920000";
    localparam string V_WRAP = "02000000002a3c970e12345608004500002fffff40000106444dc0a85a01c0a85a2ac8220017fffffffe0000000150180001b30d0000ffffffffffffff";

    // The endpoints the vectors use
    localparam logic [47:0] CLIENT_MAC  = 48'h3c970e123456;
    localparam logic [47:0] SERVER_MAC  = 48'h02000000002a;
    localparam logic [31:0] CLIENT_IP   = 32'hc0a85a01;
    localparam logic [31:0] SERVER_IP   = 32'hc0a85a2a;
    localparam logic [15:0] CLIENT_PORT = 16'd51234;
    localparam logic [15:0] SERVER_PORT = 16'd23;

    integer errors = 0;
    integer checks = 0;

    //----------------------------------------------------------------
    // Helpers
    //----------------------------------------------------------------
    function automatic tcp_hdr_t hdr(input bit c2s, input logic [31:0] seq, input logic [31:0] ack,
                                     input logic [7:0] flags, input logic [15:0] window,
                                     input logic [15:0] mss, input logic [15:0] ip_id,
                                     input logic [7:0] ttl);
        tcp_hdr_t h = '0;
        h.dst_mac  = c2s ? SERVER_MAC  : CLIENT_MAC;
        h.src_mac  = c2s ? CLIENT_MAC  : SERVER_MAC;
        h.src_ip   = c2s ? CLIENT_IP   : SERVER_IP;
        h.dst_ip   = c2s ? SERVER_IP   : CLIENT_IP;
        h.src_port = c2s ? CLIENT_PORT : SERVER_PORT;
        h.dst_port = c2s ? SERVER_PORT : CLIENT_PORT;
        h.ip_id    = ip_id;
        h.df       = 1'b1;
        h.ttl      = ttl;
        h.seq      = seq;
        h.ack      = ack;
        h.flags    = flags;
        h.window   = window;
        h.urgent   = 16'h0000;
        h.mss      = mss;
        return h;
    endfunction

    task automatic check(input bit ok, input string what);
        checks = checks + 1;
        if (!ok) begin
            errors = errors + 1;
            $error("%s", what);
        end
    endtask

    // Build from the record, compare with the vector; parse the vector,
    // compare every field and the payload
    task automatic check_vector(input string name, input string vec, input tcp_hdr_t h,
                                input bytes_t payload);
        bytes_t   golden = bytes_from_hex(vec);
        bytes_t   built  = build_frame(h, payload);
        tcp_hdr_t p;
        string    err;
        bit       ok;

        check(golden.size() > 0, {name, ": vector decodes"});
        check(bytes_eq(built, golden),
              $sformatf("%s: built frame differs\n  built  %s\n  golden %s", name, bytes_hex(built), bytes_hex(golden)));

        parse_frame(golden, p, err, ok);
        check(ok, {name, ": golden frame parses: ", err});
        check(p == h, $sformatf("%s: parsed record differs\n  parsed %s\n  given  %s", name, hdr_str(p), hdr_str(h)));
        check(bytes_eq(frame_payload(golden), payload), {name, ": parsed payload differs"});
    endtask

    // Damage a golden frame in one place and expect a given refusal
    task automatic check_refused(input string name, input string vec, input int at,
                                 input logic [7:0] xor_mask, input string reason);
        bytes_t   f = bytes_from_hex(vec);
        tcp_hdr_t p;
        string    err;
        bit       ok;
        f[at] = f[at] ^ xor_mask;
        parse_frame(f, p, err, ok);
        check(!ok && err == reason,
              $sformatf("%s: expected refusal '%s', got ok=%0d err='%s'", name, reason, ok, err));
    endtask

    //----------------------------------------------------------------
    // Test sequence
    //----------------------------------------------------------------
    bytes_t   f;
    bytes_t   seg;
    bytes_t   pl;
    tcp_hdr_t h;
    tcp_hdr_t p;
    string    err;
    bit       ok;
    int       n;
    logic [15:0] csum;

    initial begin
        //------------------------------------------------------------
        // 1. Published IPv4 header checksum example (RFC 1071 flavour,
        //    the one every textbook prints)
        //------------------------------------------------------------
        f = bytes_from_hex("450000730000400040110000c0a80001c0a800c7");
        check(ip_checksum(f, 0) == 16'hb861, $sformatf("published IP checksum: got %04x, expected b861", ip_checksum(f, 0)));
        f = bytes_from_hex("45000073000040004011b861c0a80001c0a800c7");
        check(csum_verifies(ones_sum(f, 0, 20, 32'h0)), "published IP header with its checksum verifies");

        //------------------------------------------------------------
        // 2. Golden frames, built and parsed
        //------------------------------------------------------------
        check_vector("syn",     V_SYN,     hdr(1, 32'h1A2B3C4D, 32'h0,        F_SYN,       16'd64240, 16'd1460, 16'h4E21, 8'd64), bytes_new(0));
        check_vector("syn_ack", V_SYN_ACK, hdr(0, 32'h00001000, 32'h1A2B3C4E, F_SYN|F_ACK, 16'd2048,  16'd1460, 16'h0000, 8'd64), bytes_new(0));
        check_vector("ack",     V_ACK,     hdr(1, 32'h1A2B3C4E, 32'h00001001, F_ACK,       16'd64240, 16'd0,    16'h4E22, 8'd64), bytes_new(0));
        check_vector("data",    V_DATA,    hdr(1, 32'h1A2B3C4E, 32'h00001001, F_PSH|F_ACK, 16'd64240, 16'd0,    16'h4E23, 8'd64), bytes_from_hex("68656c6c6f"));
        check_vector("echo",    V_ECHO,    hdr(0, 32'h00001001, 32'h1A2B3C53, F_PSH|F_ACK, 16'd2043,  16'd0,    16'h0000, 8'd64), bytes_from_hex("68656c6c6f"));
        check_vector("odd",     V_ODD,     hdr(1, 32'h1A2B3C53, 32'h00001006, F_PSH|F_ACK, 16'd64240, 16'd0,    16'h4E24, 8'd64), bytes_from_hex("616263"));
        check_vector("fin",     V_FIN,     hdr(1, 32'h1A2B3C56, 32'h00001006, F_FIN|F_ACK, 16'd64240, 16'd0,    16'h4E25, 8'd64), bytes_new(0));
        check_vector("rst",     V_RST,     hdr(0, 32'h00001006, 32'h1A2B3C57, F_RST|F_ACK, 16'd0,     16'd0,    16'h0000, 8'd64), bytes_new(0));
        check_vector("wrap",    V_WRAP,    hdr(1, 32'hFFFFFFFE, 32'h00000001, F_PSH|F_ACK, 16'd1,     16'd0,    16'hFFFF, 8'd1),  bytes_from_hex("ffffffffffffff"));

        //------------------------------------------------------------
        // 3. The L4 unit alone, the socket's own input, parses with
        //    the addresses supplied beside it
        //------------------------------------------------------------
        f   = bytes_from_hex(V_DATA);
        seg = frame_l4(f);
        check(seg.size() == 25, $sformatf("data L4 unit is %0d bytes, expected 25", seg.size()));
        p = '0;
        parse_tcp(CLIENT_IP, SERVER_IP, seg, p, err, ok);
        check(ok, {"data L4 unit parses: ", err});
        check(p.seq == 32'h1A2B3C4E && p.ack == 32'h00001001 && p.flags == (F_PSH|F_ACK) && p.mss == 16'h0,
              {"data L4 unit fields: ", hdr_str(p)});
        check(bytes_eq(tcp_payload(seg), bytes_from_hex("68656c6c6f")), "data L4 unit payload");
        p = '0;
        parse_tcp(CLIENT_IP, CLIENT_IP, seg, p, err, ok);
        check(!ok && err == "TCP checksum", "data L4 unit with the wrong pseudo-header is refused");

        //------------------------------------------------------------
        // 4. Refusals, one damage each
        //------------------------------------------------------------
        check_refused("payload bit",        V_DATA, 54 + 2, 8'h01, "TCP checksum");
        check_refused("tcp header bit",     V_DATA, 34 + 4, 8'h80, "TCP checksum");
        check_refused("ip header bit",      V_DATA, 14 + 8, 8'h01, "IP checksum");
        check_refused("ethertype",          V_DATA, 13,     8'h06, "EtherType");
        check_refused("ihl 6",              V_DATA, 14,     8'h03, "IP version/IHL");
        check_refused("more fragments",     V_DATA, 20,     8'h20, "fragment");
        check_refused("fragment offset",    V_DATA, 21,     8'h01, "fragment");
        check_refused("protocol udp",       V_DATA, 23,     8'h17, "IP protocol");
        check_refused("total length short", V_DATA, 17,     8'h2d ^ 8'h27, "total length too small");
        check_refused("total length long",  V_DATA, 17,     8'h2d ^ 8'h3d, "total length past the frame");
        check_refused("data offset 4",      V_DATA, 34 + 12, 8'h50 ^ 8'h40, "data offset below 5");
        check_refused("data offset 8",      V_DATA, 34 + 12, 8'h50 ^ 8'h80, "data offset past the segment");

        // A short frame padded to the Ethernet minimum parses, and the
        // padding is neither payload nor checksummed
        f  = bytes_cat(bytes_from_hex(V_ACK), bytes_new(6));
        check(f.size() == 60, "padded ACK is 60 bytes");
        parse_frame(f, p, err, ok);
        check(ok, {"padded ACK parses: ", err});
        pl = frame_payload(f);
        check(pl.size() == 0, "padded ACK has no payload");

        // Truncated below the three headers
        f  = bytes_slice(bytes_from_hex(V_ACK), 0, 53);
        parse_frame(f, p, err, ok);
        check(!ok && err == "shorter than the three headers", "truncated frame is refused");

        //------------------------------------------------------------
        // 5. Option lists the builder never produces
        //------------------------------------------------------------
        // NOP NOP MSS, then window scale (kind 3, length 3), then EOL,
        // in a 32-byte header; checksum recomputed after assembly
        h   = hdr(1, 32'h10, 32'h20, F_SYN, 16'd100, 16'd0, 16'h1, 8'd64);
        seg = build_tcp(h, bytes_new(0));
        seg = bytes_cat(seg, bytes_from_hex("0101020405b4030307000000"));  // NOP NOP MSS WS EOL pad, 12 bytes
        seg[12] = 8'h80;  // data offset 8
        seg[16] = 8'h00;
        seg[17] = 8'h00;
        csum = tcp_checksum(h.src_ip, h.dst_ip, seg);
        seg[16] = csum[15:8];
        seg[17] = csum[7:0];
        p = '0;
        parse_tcp(h.src_ip, h.dst_ip, seg, p, err, ok);
        check(ok, {"NOP NOP MSS WS EOL list parses: ", err});
        check(p.mss == 16'd1460, $sformatf("MSS behind two NOPs: got %0d", p.mss));
        pl = tcp_payload(seg);
        check(pl.size() == 0, "option-only segment has no payload");

        // The same list with the window-scale length byte (seg[27])
        // pointing past the header
        seg[27] = 8'h09;
        seg[16] = 8'h00;
        seg[17] = 8'h00;
        csum = tcp_checksum(h.src_ip, h.dst_ip, seg);
        seg[16] = csum[15:8];
        seg[17] = csum[7:0];
        p = '0;
        parse_tcp(h.src_ip, h.dst_ip, seg, p, err, ok);
        check(!ok && err == "bad option length", {"option past the header is refused: ", err});

        // An option kind with no room for its length byte
        seg = build_tcp(h, bytes_new(0));
        seg = bytes_cat(seg, bytes_from_hex("01010103"));
        seg[12] = 8'h60;  // data offset 6
        seg[16] = 8'h00;
        seg[17] = 8'h00;
        csum = tcp_checksum(h.src_ip, h.dst_ip, seg);
        seg[16] = csum[15:8];
        seg[17] = csum[7:0];
        p = '0;
        parse_tcp(h.src_ip, h.dst_ip, seg, p, err, ok);
        check(!ok && err == "option runs past the header", {"option without a length is refused: ", err});

        //------------------------------------------------------------
        // 6. Random round trips
        //------------------------------------------------------------
        for (int i = 0; i < 300; i++) begin
            n = $urandom_range(0, 120);
            h = '0;
            h.dst_mac  = 48'({$urandom(), $urandom()});
            h.src_mac  = 48'({$urandom(), $urandom()});
            h.src_ip   = $urandom();
            h.dst_ip   = $urandom();
            h.src_port = 16'($urandom());
            h.dst_port = 16'($urandom());
            h.ip_id    = 16'($urandom());
            h.df       = 1'($urandom());
            h.ttl      = 8'($urandom());
            h.seq      = $urandom();
            h.ack      = $urandom();
            h.flags    = 8'($urandom());
            h.window   = 16'($urandom());
            h.urgent   = 16'($urandom());
            h.mss      = ($urandom_range(0, 1) == 1) ? 16'($urandom()) : 16'h0000;
            pl = new[n];
            for (int k = 0; k < n; k++) pl[k] = 8'($urandom());
            f  = build_frame(h, pl);
            check(f.size() == 54 + (h.mss != 0 ? 4 : 0) + n, $sformatf("random %0d: frame size", i));
            parse_frame(f, p, err, ok);
            check(ok, $sformatf("random %0d: parses: %s", i, err));
            check(p == h, $sformatf("random %0d: record round trip\n  parsed %s\n  given  %s", i, hdr_str(p), hdr_str(h)));
            check(bytes_eq(frame_payload(f), pl), $sformatf("random %0d: payload round trip", i));
            // and the L4 unit alone
            seg = frame_l4(f);
            p = '0;
            parse_tcp(h.src_ip, h.dst_ip, seg, p, err, ok);
            check(ok && p.seq == h.seq && p.ack == h.ack && p.flags == h.flags && p.mss == h.mss
                  && p.window == h.window && p.src_port == h.src_port && p.dst_port == h.dst_port,
                  $sformatf("random %0d: L4 round trip", i));
        end

        //------------------------------------------------------------
        // 7. Sequence space
        //------------------------------------------------------------
        h = '0;
        check(seg_len(h, 0) == 0, "seg_len of a pure ACK is 0");
        check(seg_len(h, 7) == 7, "seg_len of 7 bytes is 7");
        h.flags = F_SYN;
        check(seg_len(h, 0) == 1, "seg_len of a SYN is 1");
        h.flags = F_FIN | F_ACK;
        check(seg_len(h, 3) == 4, "seg_len of FIN with 3 bytes is 4");
        h.flags = F_SYN | F_FIN;
        check(seg_len(h, 0) == 2, "seg_len of SYN+FIN is 2");

        check(seq_lt(32'hFFFFFFF0, 32'h00000010), "seq_lt across the wrap");
        check(!seq_lt(32'h00000010, 32'hFFFFFFF0), "seq_lt across the wrap, reversed");
        check(seq_lt(32'd5, 32'd6), "seq_lt 5 < 6");
        check(!seq_lt(32'd6, 32'd6), "seq_lt not 6 < 6");
        check(seq_le(32'd6, 32'd6), "seq_le 6 <= 6");
        check(!seq_le(32'd7, 32'd6), "seq_le not 7 <= 6");
        check(seq_lt(32'h80000001, 32'h00000000), "seq_lt just under half the space");
        check(!seq_lt(32'h7FFFFFFF, 32'h00000000), "seq_lt just over half the space");

        //------------------------------------------------------------
        // Verdict
        //------------------------------------------------------------
        $display("tcp_model_pkg_tb: %0d checks", checks);
        if (errors == 0)
            $display("tcp_model_pkg_tb: ALL TESTS PASSED");
        else
            $display("tcp_model_pkg_tb: %0d ERROR(S)", errors);
        $finish;
    end

endmodule
