# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/cmpgt_tb.v
TESTBENCH_MODULE  = cmpgt_tb

VCD_FILE          = cmpgt_tb.vcd

TOP_FILE          = ../src/cmpgt.v
TOP_MODULE        = cmpgt

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/xilinx.mk
include ../../../Makefiles/common.mk
