# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/quad_encoder_tb.v
TESTBENCH_MODULE  = quad_encoder_tb

VCD_FILE          = quad_encoder_tb.vcd

TOP_FILE          = ../src/quad_encoder.v
TOP_MODULE        = quad_encoder

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/xilinx.mk
