# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= quad_encoder
TOP_FILE          ?= ../src/quad_encoder.v
TOP_DEPS          ?=

TESTBENCH_MODULE  ?= quad_encoder_tb
TESTBENCH_FILE    ?= ../src/quad_encoder_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
