# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/uart_reg_if_tb.v
TESTBENCH_MODULE  = uart_reg_if_tb

VCD_FILE          = uart_reg_if_tb.vcd

TOP_FILE          = ../src/uart_reg_if.v
TOP_MODULE        = uart_reg_if

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/xilinx.mk
