# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= uart_reg_if
TOP_FILE          ?= ../src/uart_reg_if.v

TESTBENCH_MODULE  ?= uart_reg_if_tb
TESTBENCH_FILE    ?= ../src/uart_reg_if_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/vivado.mk
