# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= rdselh
TOP_FILE          ?= ../src/rdselh.v

TESTBENCH_MODULE  ?= rdselh_tb
TESTBENCH_FILE    ?= ../src/rdselh_tb.v


include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
include ../../../Makefiles/yosys.mk
include ../../../Makefiles/common.mk
