# SPDX-License-Identifier: CERN-OHL-P-2.0
# Copyright (c) 2013-2026 Christophe Clienti

TOP_MODULE        ?= vliwrf
TOP_FILE          ?= ../src/vliwrf.sv
TOP_DEPS          ?= ../../nrpmem

TESTBENCH_MODULE  ?= vliwrf_tb
TESTBENCH_FILE    ?= ../src/vliwrf_tb.sv


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
