# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= gray2bin
TOP_FILE          ?= ../src/gray2bin.v

TESTBENCH_MODULE  ?= gray2bin_tb
TESTBENCH_FILE    ?= ../src/gray2bin_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
