# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/gray2bin_tb.v
TESTBENCH_MODULE  = gray2bin_tb

VCD_FILE          = gray2bin_tb.vcd

TOP_FILE          = ../src/gray2bin.v
TOP_MODULE        = gray2bin

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
