# Logic Unit Makefile
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= hynoc_prra
TOP_FILE          ?= ../src/hynoc_prra.v
TOP_DEPS          ?= ../../../../lib/prra_lut/src/prra_lut.v

TESTBENCH_MODULE  ?= hynoc_prra_tb
TESTBENCH_FILE    ?= ../src/hynoc_prra_tb.v


include ../../../../Makefiles/common.mk
include ../../../../Makefiles/iverilog.mk
include ../../../../Makefiles/verilator.mk
include ../../../../Makefiles/xilinx.mk
