# Hynoc stream writer Makefile
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_MODULE  = hynoc_stream_writer_tb

TESTBENCH_FILE    = ../src/hynoc_stream_writer_tb.v

VCD_FILE          = hynoc_stream_writer_tb.vcd

TOP_FILE          = ../src/hynoc_stream_writer.v
TOP_MODULE        = hynoc_stream_writer

TESTBENCH_DEPS    =

TOP_DEPS          =

include ../../../../Makefiles/common.mk
include ../../../../Makefiles/iverilog.mk
