# Hynoc stream writer Makefile
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= hynoc_stream_writer
TOP_FILE          ?= ../src/hynoc_stream_writer.v

TESTBENCH_MODULE  ?= hynoc_stream_writer_tb
TESTBENCH_FILE    ?= ../src/hynoc_stream_writer_tb.v


include ../../../../Makefiles/common.mk
include ../../../../Makefiles/iverilog.mk
