# Component Library
# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/simple_uart_tb.v
TESTBENCH_MODULE  = simple_uart_tb

VCD_FILE          = simple_uart_tb.vcd

TOP_FILE          = ../src/simple_uart.v
TOP_MODULE        = simple_uart

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/xilinx.mk
include ../../../Makefiles/common.mk
