# Component Library
# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= simple_uart
TOP_FILE          ?= ../src/simple_uart.v
TOP_DEPS          ?= ../src/simple_uart_rx.v ../src/simple_uart_tx.v

TESTBENCH_MODULE  ?= simple_uart_tb
TESTBENCH_FILE    ?= ../src/simple_uart_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/xilinx.mk
