# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= sclkfifolut
TOP_FILE          ?= ../src/sclkfifolut.v

TESTBENCH_MODULE  ?= sclkfifolut_tb
TESTBENCH_FILE    ?= ../src/sclkfifolut_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
include ../../../Makefiles/common.mk
