# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/sclkfifolut_tb.v
TESTBENCH_MODULE  = sclkfifolut_tb

VCD_FILE          = sclkfifolut_tb.vcd

TOP_FILE          = ../src/sclkfifolut.v
TOP_MODULE        = sclkfifolut

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
include ../../../Makefiles/common.mk
