# Hynoc stream reader Makefile
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= hynoc_stream_reader
TOP_FILE          ?= ../src/hynoc_stream_reader.v

TESTBENCH_MODULE  ?= hynoc_stream_reader_tb
TESTBENCH_FILE    ?= ../src/hynoc_stream_reader_tb.v
TESTBENCH_DEPS    ?= ../../hynoc_stream_writer ../../../../lib/dclkfifolut


include ../../../../Makefiles/common.mk
include ../../../../Makefiles/iverilog.mk
