#!/usr/bin/env python3
"""Golden vectors for tcp_model_pkg_tb, from an implementation that
shares nothing with the SystemVerilog one.

Pure Python, standard library only: the headers are packed with struct
and the checksums computed by the RFC 1071 recipe over the finished
bytes. Run it and paste its output into the bench when a vector is
added; the bench names this file as their source.
"""

import struct


def ones_complement_checksum(data: bytes) -> int:
    if len(data) % 2:
        data += b"\x00"
    total = sum(struct.unpack("!%dH" % (len(data) // 2), data))
    while total >> 16:
        total = (total & 0xFFFF) + (total >> 16)
    return (~total) & 0xFFFF


def tcp_segment(src_ip, dst_ip, sport, dport, seq, ack, flags, window,
                payload=b"", mss=None, urgent=0):
    options = struct.pack("!BBH", 2, 4, mss) if mss is not None else b""
    doff = (20 + len(options)) // 4
    hdr = struct.pack("!HHIIBBHHH", sport, dport, seq, ack, doff << 4,
                      flags, window, 0, urgent) + options
    pseudo = struct.pack("!4s4sBBH", src_ip, dst_ip, 0, 6, len(hdr) + len(payload))
    csum = ones_complement_checksum(pseudo + hdr + payload)
    hdr = hdr[:16] + struct.pack("!H", csum) + hdr[18:]
    return hdr + payload


def ipv4_packet(src_ip, dst_ip, ip_id, ttl, l4, df=True):
    total = 20 + len(l4)
    flags_frag = (0x4000 if df else 0)
    hdr = struct.pack("!BBHHHBBH4s4s", 0x45, 0, total, ip_id, flags_frag,
                      ttl, 6, 0, src_ip, dst_ip)
    csum = ones_complement_checksum(hdr)
    hdr = hdr[:10] + struct.pack("!H", csum) + hdr[12:]
    return hdr + l4


def eth_frame(dst_mac, src_mac, ip):
    return dst_mac + src_mac + struct.pack("!H", 0x0800) + ip


def ip(a):
    return bytes(int(x) for x in a.split("."))


def mac(m):
    return bytes.fromhex(m.replace(":", ""))


CLIENT_MAC = mac("3c:97:0e:12:34:56")
SERVER_MAC = mac("02:00:00:00:00:2a")
CLIENT_IP = ip("192.168.90.1")
SERVER_IP = ip("192.168.90.42")
CLIENT_PORT = 51234
SERVER_PORT = 23

FIN, SYN, RST, PSH, ACK = 0x01, 0x02, 0x04, 0x08, 0x10

VECTORS = [
    # name, direction c2s/s2c, seq, ack, flags, window, payload, mss, ip_id, ttl
    ("syn",      "c2s", 0x1A2B3C4D, 0,          SYN,      64240, b"",        1460, 0x4E21, 64),
    ("syn_ack",  "s2c", 0x00001000, 0x1A2B3C4E, SYN|ACK,  2048,  b"",        1460, 0,      64),
    ("ack",      "c2s", 0x1A2B3C4E, 0x00001001, ACK,      64240, b"",        None, 0x4E22, 64),
    ("data",     "c2s", 0x1A2B3C4E, 0x00001001, PSH|ACK,  64240, b"hello",   None, 0x4E23, 64),
    ("echo",     "s2c", 0x00001001, 0x1A2B3C53, PSH|ACK,  2043,  b"hello",   None, 0,      64),
    ("odd",      "c2s", 0x1A2B3C53, 0x00001006, PSH|ACK,  64240, b"abc",     None, 0x4E24, 64),
    ("fin",      "c2s", 0x1A2B3C56, 0x00001006, FIN|ACK,  64240, b"",        None, 0x4E25, 64),
    ("rst",      "s2c", 0x00001006, 0x1A2B3C57, RST|ACK,  0,     b"",        None, 0,      64),
    ("wrap",     "c2s", 0xFFFFFFFE, 0x00000001, PSH|ACK,  1,     b"\xff"*7,  None, 0xFFFF, 1),
]


def main():
    print("    // Generated by project/gen_vectors.py, do not edit by hand")
    for name, direction, seq, ack, flags, window, payload, mss, ip_id, ttl in VECTORS:
        if direction == "c2s":
            smac, dmac, sip, dip, sport, dport = CLIENT_MAC, SERVER_MAC, CLIENT_IP, SERVER_IP, CLIENT_PORT, SERVER_PORT
        else:
            smac, dmac, sip, dip, sport, dport = SERVER_MAC, CLIENT_MAC, SERVER_IP, CLIENT_IP, SERVER_PORT, CLIENT_PORT
        seg = tcp_segment(sip, dip, sport, dport, seq, ack, flags, window, payload, mss)
        frame = eth_frame(dmac, smac, ipv4_packet(sip, dip, ip_id, ttl, seg))
        print(f'    localparam string V_{name.upper()} = "{frame.hex()}";')


if __name__ == "__main__":
    main()
