# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= pwm_generator
TOP_FILE          ?= ../src/pwm_generator.v

TESTBENCH_MODULE  ?= pwm_generator_tb
TESTBENCH_FILE    ?= ../src/pwm_generator_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/vivado.mk
