QUARTUS_TOP_MODULE    = de0_nano
QUARTUS_FAMILY        = "Cyclone IV E"
QUARTUS_PART          = EP4CE22F17C6
QUARTUS_BOARDFILE     = ../../../boards/de0_nano/de0_nano_pin.tcl
QUARTUS_CONSTRAINTS   = ../../../boards/de0_nano/de0_nano.sdc
QUARTUS_CUSTOM_SCRIPT = quartus_custom_script.tcl

include ../../../Makefiles/quartus.mk
include ../../../Makefiles/common.mk
