TOP_MODULE            = de0_nano
TOP_FILE              = ../src/de0_nano.v
TOP_DEPS              = ../../../lib/simple_uart ../../uart_reg_if

QUARTUS_FAMILY        = "Cyclone IV E"
QUARTUS_PART          = EP4CE22F17C6
QUARTUS_BOARDFILE     = ../../../boards/de0_nano/de0_nano_pin.tcl
QUARTUS_CONSTFILE     = ../../../boards/de0_nano/de0_nano_pin.sdc
QUARTUS_CUSTOM_SCRIPT = quartus_custom_script.tcl

include ../../../Makefiles/common.mk
include ../../../Makefiles/quartus.mk
