# SPDX-License-Identifier: CERN-OHL-P-2.0
# Copyright (c) 2013-2026 Christophe Clienti

TOP_MODULE        ?= nrpmem
TOP_FILE          ?= ../src/nrpmem.sv

TESTBENCH_MODULE  ?= nrpmem_tb
TESTBENCH_FILE    ?= ../src/nrpmem_tb.sv


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
