# Copyright (C) 2025 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= axi_stream_upsizer
TOP_FILE          ?= ../src/axi_stream_upsizer.sv
TOP_DEPS          ?=

TESTBENCH_MODULE  ?= axi_stream_upsizer_tb
TESTBENCH_FILE    ?= ../src/axi_stream_upsizer_tb.sv


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
