# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= adderc
TOP_FILE          ?= ../src/adderc.v

TESTBENCH_MODULE  ?= adderc_tb
TESTBENCH_FILE    ?= ../src/adderc_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
