// SPDX-License-Identifier: CERN-OHL-P-2.0
// Copyright (c) 2026 Christophe Clienti
//
// This source describes Open Hardware and is licensed under the CERN-OHL-P v2.
// You may redistribute and modify this file under the terms of the CERN-OHL-P v2
// (https://ohwr.org/cern_ohl_p_v2.txt).
//
// This source is distributed WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING
// OF MERCHANTABILITY, SATISFACTORY QUALITY AND FITNESS FOR A PARTICULAR PURPOSE.
// Please see the CERN-OHL-P v2 for applicable conditions.

//-----------------------------------------------------------------------------
// Title         : UDP Model Package
//-----------------------------------------------------------------------------
// File          : udp_model_pkg_tb.sv
// Author        : Christophe Clienti <cclienti@wavecruncher.net>
// Created       : 2026-09-14
// Last modified : 2026-09-14
//-----------------------------------------------------------------------------
// Description: Self-check of udp_model_pkg. The builders are anchored
// to five whole frames produced by project/gen_vectors.py, a pure
// Python implementation that shares nothing with the package, and the
// IPv4 checksum to the published RFC 1071 example; the parsers must
// accept those frames and give back every field. Then the parsers are
// shown to refuse each kind of damage they are meant to catch, and a
// few hundred random headers and payloads go through build and parse
// and back, checksum enabled and disabled both.
//
// Reports udp_model_pkg_tb: ALL TESTS PASSED or N ERROR(S).

`timescale 1 ns / 100 ps

module udp_model_pkg_tb;
    import udp_model_pkg::*;

    //----------------------------------------------------------------
    // Golden vectors
    //----------------------------------------------------------------
    // Generated by project/gen_vectors.py, do not edit by hand
    localparam string V_REQ = "02000000002a3c970e1234560800450000214e2140004011b72ec0a85a01c0a85a2ac8220007000dbe5b68656c6c6f";
    localparam string V_REPLY = "3c970e12345602000000002a0800450000210000400040110550c0a85a2ac0a85a010007c822000dbe5b68656c6c6f";
    localparam string V_EMPTY = "02000000002a3c970e12345608004500001c4e2240004011b732c0a85a01c0a85a2ac822000700080238";
    localparam string V_ODD = "02000000002a3c970e12345608004500001f4e2340004011b72ec0a85a01c0a85a2ac8220007000b3dcf616263";
    localparam string V_NO_CHECKSUM = "02000000002a3c970e1234560800450000224e2440004011b72ac0a85a01c0a85a2ac8220007000e00006e6f6373756d";

    // The endpoints the vectors use
    localparam logic [47:0] CLIENT_MAC  = 48'h3c970e123456;
    localparam logic [47:0] SERVER_MAC  = 48'h02000000002a;
    localparam logic [31:0] CLIENT_IP   = 32'hc0a85a01;
    localparam logic [31:0] SERVER_IP   = 32'hc0a85a2a;
    localparam logic [15:0] CLIENT_PORT = 16'd51234;
    localparam logic [15:0] SERVER_PORT = 16'd7;

    integer errors = 0;
    integer checks = 0;

    //----------------------------------------------------------------
    // Helpers
    //----------------------------------------------------------------
    function automatic udp_hdr_t hdr(input bit c2s, input logic [15:0] ip_id, input logic [7:0] ttl,
                                     input bit no_checksum);
        udp_hdr_t h = '0;
        h.dst_mac      = c2s ? SERVER_MAC  : CLIENT_MAC;
        h.src_mac      = c2s ? CLIENT_MAC  : SERVER_MAC;
        h.src_ip       = c2s ? CLIENT_IP   : SERVER_IP;
        h.dst_ip       = c2s ? SERVER_IP   : CLIENT_IP;
        h.src_port     = c2s ? CLIENT_PORT : SERVER_PORT;
        h.dst_port     = c2s ? SERVER_PORT : CLIENT_PORT;
        h.ip_id        = ip_id;
        h.df           = 1'b1;
        h.ttl          = ttl;
        h.no_checksum  = no_checksum;
        return h;
    endfunction

    task automatic check(input bit ok, input string what);
        checks = checks + 1;
        if (!ok) begin
            errors = errors + 1;
            $error("%s", what);
        end
    endtask

    // Build from the record, compare with the vector; parse the vector,
    // compare every field and the payload
    task automatic check_vector(input string name, input string vec, input udp_hdr_t h,
                                input bytes_t payload);
        bytes_t   golden = bytes_from_hex(vec);
        bytes_t   built  = build_frame(h, payload);
        udp_hdr_t p;
        string    err;
        bit       ok;

        check(golden.size() > 0, {name, ": vector decodes"});
        check(bytes_eq(built, golden),
              $sformatf("%s: built frame differs\n  built  %s\n  golden %s", name, bytes_hex(built), bytes_hex(golden)));

        parse_frame(golden, p, err, ok);
        check(ok, {name, ": golden frame parses: ", err});
        check(p == h, $sformatf("%s: parsed record differs\n  parsed %s\n  given  %s", name, hdr_str(p), hdr_str(h)));
        check(bytes_eq(frame_payload(golden), payload), {name, ": parsed payload differs"});
    endtask

    // Damage a golden frame in one place and expect a given refusal
    task automatic check_refused(input string name, input string vec, input int at,
                                 input logic [7:0] xor_mask, input string reason);
        bytes_t   f = bytes_from_hex(vec);
        udp_hdr_t p;
        string    err;
        bit       ok;
        f[at] = f[at] ^ xor_mask;
        parse_frame(f, p, err, ok);
        check(!ok && err == reason,
              $sformatf("%s: expected refusal '%s', got ok=%0d err='%s'", name, reason, ok, err));
    endtask

    //----------------------------------------------------------------
    // Test sequence
    //----------------------------------------------------------------
    bytes_t   f;
    bytes_t   seg;
    bytes_t   pl;
    udp_hdr_t h;
    udp_hdr_t p;
    string    err;
    bit       ok;
    int       n;

    initial begin
        //------------------------------------------------------------
        // 1. Published IPv4 header checksum example (RFC 1071 flavour,
        //    the one every textbook prints), shared with tcp_model_pkg
        //    since it exercises ip_checksum alone
        //------------------------------------------------------------
        f = bytes_from_hex("450000730000400040110000c0a80001c0a800c7");
        check(ip_checksum(f, 0) == 16'hb861, $sformatf("published IP checksum: got %04x, expected b861", ip_checksum(f, 0)));
        f = bytes_from_hex("45000073000040004011b861c0a80001c0a800c7");
        check(csum_verifies(ones_sum(f, 0, 20, 32'h0)), "published IP header with its checksum verifies");

        check(csum_fold(32'hFFFFFFFF) == 16'h0000, $sformatf("csum_fold double carry: got %04x", csum_fold(32'hFFFFFFFF)));
        check(csum_fold(32'h0001FFFF) == 16'hFFFE, $sformatf("csum_fold second double carry: got %04x", csum_fold(32'h0001FFFF)));

        pl = bytes_from_hex("abc");
        check(pl.size() == 0, "odd-length hex string is rejected");
        pl = bytes_from_hex("00gg");
        check(pl.size() == 0, "non-hex character is rejected");
        pl = bytes_from_hex("00ff");
        check(pl.size() == 2 && pl[0] == 8'h00 && pl[1] == 8'hff, "clean hex pair decodes");

        //------------------------------------------------------------
        // 2. Golden frames, built and parsed
        //------------------------------------------------------------
        check_vector("req",         V_REQ,         hdr(1, 16'h4E21, 8'd64, 1'b0), bytes_from_hex("68656c6c6f"));
        check_vector("reply",       V_REPLY,       hdr(0, 16'h0000, 8'd64, 1'b0), bytes_from_hex("68656c6c6f"));
        check_vector("empty",       V_EMPTY,       hdr(1, 16'h4E22, 8'd64, 1'b0), bytes_new(0));
        check_vector("odd",         V_ODD,         hdr(1, 16'h4E23, 8'd64, 1'b0), bytes_from_hex("616263"));
        check_vector("no_checksum", V_NO_CHECKSUM, hdr(1, 16'h4E24, 8'd64, 1'b1), bytes_from_hex("6e6f6373756d"));

        // RFC 768's one edge case: a computed checksum of zero must be
        // sent as all ones, since zero on the wire means "no
        // checksum". Found by search, not by hand, the same way the
        // TCP model's directed vectors were: zero addresses and ports,
        // payload 0xff 0xda, computed sum folds to exactly 0x0000.
        h = '0;
        h.src_ip = 32'h0;
        h.dst_ip = 32'h0;
        seg = build_udp(h, bytes_from_hex("ffda"));
        check({seg[6], seg[7]} == 16'hFFFF,
              $sformatf("computed-zero checksum sent as FFFF: got %04x", {seg[6], seg[7]}));
        p = '0;
        parse_udp(32'h0, 32'h0, seg, p, err, ok);
        check(ok && !p.no_checksum, {"computed-zero checksum still verifies: ", err});

        //------------------------------------------------------------
        // 3. The L4 unit alone, the socket's own input, parses with
        //    the addresses supplied beside it
        //------------------------------------------------------------
        f   = bytes_from_hex(V_REQ);
        seg = frame_l4(f);
        check(seg.size() == 13, $sformatf("req L4 unit is %0d bytes, expected 13", seg.size()));
        p = '0;
        parse_udp(CLIENT_IP, SERVER_IP, seg, p, err, ok);
        check(ok, {"req L4 unit parses: ", err});
        check(p.src_port == CLIENT_PORT && p.dst_port == SERVER_PORT && !p.no_checksum,
              {"req L4 unit fields: ", hdr_str(p)});
        check(bytes_eq(udp_payload(seg), bytes_from_hex("68656c6c6f")), "req L4 unit payload");
        p = '0;
        parse_udp(CLIENT_IP, CLIENT_IP, seg, p, err, ok);
        check(!ok && err == "UDP checksum", "req L4 unit with the wrong pseudo-header is refused");

        //------------------------------------------------------------
        // 4. Refusals, one damage each
        //------------------------------------------------------------
        check_refused("payload bit",        V_REQ, 42 + 2, 8'h01, "UDP checksum");
        check_refused("udp header bit",     V_REQ, 34,      8'h01, "UDP checksum");
        check_refused("ip header bit",      V_REQ, 14 + 8,  8'h01, "IP checksum");
        check_refused("ethertype",          V_REQ, 13,      8'h06, "EtherType");
        check_refused("ihl 6",              V_REQ, 14,      8'h03, "IP version/IHL");
        check_refused("more fragments",     V_REQ, 20,      8'h20, "fragment");
        check_refused("fragment offset",    V_REQ, 21,      8'h01, "fragment");
        check_refused("protocol tcp",       V_REQ, 23,      8'h17, "IP protocol");
        check_refused("total length short", V_REQ, 17,      8'h21 ^ 8'h1b, "total length too small");
        check_refused("total length long",  V_REQ, 17,      8'h21 ^ 8'h31, "total length past the frame");
        check_refused("udp length field",   V_REQ, 34 + 5,  8'h01, "length field");

        // A short frame padded to the Ethernet minimum parses, and the
        // padding is neither payload nor checksummed
        f  = bytes_cat(bytes_from_hex(V_EMPTY), bytes_new(18));
        check(f.size() == 60, "padded empty datagram is 60 bytes");
        parse_frame(f, p, err, ok);
        check(ok, {"padded empty datagram parses: ", err});
        pl = frame_payload(f);
        check(pl.size() == 0, "padded empty datagram has no payload");

        // Truncated below the three headers
        f  = bytes_slice(bytes_from_hex(V_EMPTY), 0, 41);
        parse_frame(f, p, err, ok);
        check(!ok && err == "shorter than the three headers", "truncated frame is refused");

        // parse_udp fed a segment shorter than a UDP header, its own
        // guard: parse_frame never lets one through, so this is the
        // only path that reaches it
        seg = bytes_slice(frame_l4(bytes_from_hex(V_REQ)), 0, 4);
        p = '0;
        parse_udp(CLIENT_IP, SERVER_IP, seg, p, err, ok);
        check(!ok && err == "shorter than a UDP header", "short L4 unit is refused");

        //------------------------------------------------------------
        // 5. Random round trips, checksum enabled and disabled both
        //------------------------------------------------------------
        for (int i = 0; i < 300; i++) begin
            n = $urandom_range(0, 200);
            h = '0;
            h.dst_mac     = 48'({$urandom(), $urandom()});
            h.src_mac     = 48'({$urandom(), $urandom()});
            h.src_ip      = $urandom();
            h.dst_ip      = $urandom();
            h.src_port    = 16'($urandom());
            h.dst_port    = 16'($urandom());
            h.ip_id       = 16'($urandom());
            h.df          = 1'($urandom());
            h.ttl         = 8'($urandom());
            h.no_checksum = 1'($urandom_range(0, 3) == 0); // 1 in 4
            pl = new[n];
            for (int k = 0; k < n; k++) pl[k] = 8'($urandom());
            f  = build_frame(h, pl);
            check(f.size() == 42 + n, $sformatf("random %0d: frame size", i));
            parse_frame(f, p, err, ok);
            check(ok, $sformatf("random %0d: parses: %s", i, err));
            check(p == h, $sformatf("random %0d: record round trip\n  parsed %s\n  given  %s", i, hdr_str(p), hdr_str(h)));
            check(bytes_eq(frame_payload(f), pl), $sformatf("random %0d: payload round trip", i));
            // and the L4 unit alone
            seg = frame_l4(f);
            p = '0;
            parse_udp(h.src_ip, h.dst_ip, seg, p, err, ok);
            check(ok && p.src_port == h.src_port && p.dst_port == h.dst_port && p.no_checksum == h.no_checksum,
                  $sformatf("random %0d: L4 round trip", i));
        end

        //------------------------------------------------------------
        // Verdict
        //------------------------------------------------------------
        $display("udp_model_pkg_tb: %0d checks", checks);
        if (errors == 0)
            $display("udp_model_pkg_tb: ALL TESTS PASSED");
        else
            $display("udp_model_pkg_tb: %0d ERROR(S)", errors);
        $finish;
    end

endmodule
