#!/usr/bin/env python3
"""Golden vectors for udp_model_pkg_tb, from an implementation that
shares nothing with the SystemVerilog one.

Pure Python, standard library only: the headers are packed with struct
and the checksums computed by the RFC 1071 recipe over the finished
bytes. Run it and paste its output into the bench when a vector is
added; the bench names this file as their source.
"""

import struct


def ones_complement_checksum(data: bytes) -> int:
    if len(data) % 2:
        data += b"\x00"
    total = sum(struct.unpack("!%dH" % (len(data) // 2), data))
    while total >> 16:
        total = (total & 0xFFFF) + (total >> 16)
    return (~total) & 0xFFFF


def udp_datagram(src_ip, dst_ip, sport, dport, payload=b"", no_checksum=False):
    length = 8 + len(payload)
    hdr = struct.pack("!HHHH", sport, dport, length, 0)
    dgram = hdr + payload
    if no_checksum:
        return dgram
    pseudo = struct.pack("!4s4sBBH", src_ip, dst_ip, 0, 17, length)
    csum = ones_complement_checksum(pseudo + dgram)
    if csum == 0:
        csum = 0xFFFF
    return dgram[:6] + struct.pack("!H", csum) + dgram[8:]


def ipv4_packet(src_ip, dst_ip, ip_id, ttl, l4, df=True):
    total = 20 + len(l4)
    flags_frag = (0x4000 if df else 0)
    hdr = struct.pack("!BBHHHBBH4s4s", 0x45, 0, total, ip_id, flags_frag,
                      ttl, 17, 0, src_ip, dst_ip)
    csum = ones_complement_checksum(hdr)
    hdr = hdr[:10] + struct.pack("!H", csum) + hdr[12:]
    return hdr + l4


def eth_frame(dst_mac, src_mac, ip):
    return dst_mac + src_mac + struct.pack("!H", 0x0800) + ip


def ip(a):
    return bytes(int(x) for x in a.split("."))


def mac(m):
    return bytes.fromhex(m.replace(":", ""))


CLIENT_MAC = mac("3c:97:0e:12:34:56")
SERVER_MAC = mac("02:00:00:00:00:2a")
CLIENT_IP = ip("192.168.90.1")
SERVER_IP = ip("192.168.90.42")
CLIENT_PORT = 51234
SERVER_PORT = 7

VECTORS = [
    # name, direction c2s/s2c, payload, no_checksum, ip_id, ttl
    ("req",         "c2s", b"hello",  False, 0x4E21, 64),
    ("reply",       "s2c", b"hello",  False, 0,      64),
    ("empty",       "c2s", b"",       False, 0x4E22, 64),
    ("odd",         "c2s", b"abc",    False, 0x4E23, 64),
    ("no_checksum", "c2s", b"nocsum", True,  0x4E24, 64),
]


def main():
    print("    // Generated by project/gen_vectors.py, do not edit by hand")
    for name, direction, payload, no_checksum, ip_id, ttl in VECTORS:
        if direction == "c2s":
            smac, dmac, sip, dip, sport, dport = CLIENT_MAC, SERVER_MAC, CLIENT_IP, SERVER_IP, CLIENT_PORT, SERVER_PORT
        else:
            smac, dmac, sip, dip, sport, dport = SERVER_MAC, CLIENT_MAC, SERVER_IP, CLIENT_IP, SERVER_PORT, CLIENT_PORT
        dgram = udp_datagram(sip, dip, sport, dport, payload, no_checksum)
        frame = eth_frame(dmac, smac, ipv4_packet(sip, dip, ip_id, ttl, dgram))
        print(f'    localparam string V_{name.upper()} = "{frame.hex()}";')


if __name__ == "__main__":
    main()
