# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_MODULE  ?= prra_lut_tb
TESTBENCH_FILE    ?= ../src/prra_lut_tb.v

TOP_MODULE        ?= prra_lut
TOP_FILE          ?= ../src/prra_lut.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
