# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/prra_lut_tb.v
TESTBENCH_MODULE  = prra_lut_tb

VCD_FILE          = prra_lut_tb.vcd

TOP_FILE          = ../src/prra_lut.v
TOP_MODULE        = prra_lut

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
