# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= multiplier
TOP_FILE          ?= ../src/multiplier.v

TESTBENCH_MODULE  ?= multiplier_tb
TESTBENCH_FILE    ?= ../src/multiplier_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
