# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= dpmemwf
TOP_FILE          ?= ../src/dpmemwf.v

TESTBENCH_MODULE  ?= dpmemwf_tb
TESTBENCH_FILE    ?= ../src/dpmemwf_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
