# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_FILE          ?= ../src/dclkfifolut.v
TOP_MODULE        ?= dclkfifolut
TOP_DEPS          ?= ../../gray2bin ../../bin2gray

TESTBENCH_MODULE  ?= dclkfifolut_tb
TESTBENCH_FILE    ?= ../src/dclkfifolut_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
