# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= dpmemrf
TOP_FILE          ?= ../src/dpmemrf.v

TESTBENCH_MODULE  ?= dpmemrf_tb
TESTBENCH_FILE    ?= ../src/dpmemrf_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
