# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/dpmemrf_tb.v
TESTBENCH_MODULE  = dpmemrf_tb

VCD_FILE          = dpmemrf_tb.vcd

TOP_FILE          = ../src/dpmemrf.v
TOP_MODULE        = dpmemrf

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/xilinx.mk
include ../../../Makefiles/yosys.mk
include ../../../Makefiles/common.mk
