# Logic Unit Makefile
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= hynoc_local_interface
TOP_FILE          ?= ../src/hynoc_local_interface.v
TOP_DEPS          ?= ../../../../lib/sclkfifolut ../../../../lib/dclkfifolut

TESTBENCH_MODULE  ?= hynoc_local_interface_tb
TESTBENCH_FILE    ?= ../src/hynoc_local_interface_tb.v


include ../../../../Makefiles/common.mk
include ../../../../Makefiles/iverilog.mk
include ../../../../Makefiles/verilator.mk
include ../../../../Makefiles/vivado.mk
