# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= rmii_mac_rx
TOP_FILE          ?= ../src/rmii_mac_rx.sv
TOP_DEPS          ?=

TESTBENCH_MODULE  ?= rmii_mac_rx_tb
TESTBENCH_FILE    ?= ../src/rmii_mac_rx_tb.sv


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
