# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= barrel
TOP_FILE          ?= ../src/barrel.v

TESTBENCH_MODULE  ?= barrel_tb
TESTBENCH_FILE    ?= ../src/barrel_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
