# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/barrel_tb.v
TESTBENCH_MODULE  = barrel_tb

VCD_FILE          = barrel_tb.vcd

TOP_FILE          = ../src/barrel.v
TOP_MODULE        = barrel

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/xilinx.mk
include ../../../Makefiles/common.mk
