# Copyright (C) 2013-2019 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= rmii_mac_tx
TOP_FILE          ?= ../src/rmii_mac_tx.sv
TOP_DEPS          ?=

TESTBENCH_MODULE  ?= rmii_mac_tx_tb
TESTBENCH_FILE    ?= ../src/rmii_mac_tx_tb.sv
TESTBENCH_DEPS    ?= ../../rmii_mac_rx/src/rmii_mac_rx.sv


include ../../../../Makefiles/common.mk
include ../../../../Makefiles/wavedisp.mk
include ../../../../Makefiles/iverilog.mk
include ../../../../Makefiles/verilator.mk
include ../../../../Makefiles/vivado.mk
