# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/rdselb_tb.v
TESTBENCH_MODULE  = rdselb_tb

VCD_FILE          = rdselb_tb.vcd

TOP_FILE          = ../src/rdselb.v
TOP_MODULE        = rdselb

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
include ../../../Makefiles/yosys.mk
include ../../../Makefiles/common.mk
