# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= rdselb
TOP_FILE          ?= ../src/rdselb.v

TESTBENCH_MODULE  ?= rdselb_tb
TESTBENCH_FILE    ?= ../src/rdselb_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/vivado.mk
