# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TESTBENCH_FILE    = ../src/cmplt_tb.v
TESTBENCH_MODULE  = cmplt_tb

VCD_FILE          = cmplt_tb.vcd

TOP_FILE          = ../src/cmplt.v
TOP_MODULE        = cmplt

TESTBENCH_DEPS    =

TOP_DEPS          =


include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
include ../../../Makefiles/yosys.mk
include ../../../Makefiles/common.mk
