# Component Library
# Copyright (C) 2013-2016 Christophe Clienti - All Rights Reserved

TOP_MODULE        ?= cmplt
TOP_FILE          ?= ../src/cmplt.v

TESTBENCH_MODULE  ?= cmplt_tb
TESTBENCH_FILE    ?= ../src/cmplt_tb.v


include ../../../Makefiles/common.mk
include ../../../Makefiles/wavedisp.mk
include ../../../Makefiles/iverilog.mk
include ../../../Makefiles/verilator.mk
include ../../../Makefiles/modelsim.mk
include ../../../Makefiles/xilinx.mk
